/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AMMInterface extends Interface {
    getFunction(nameOrSignature: "K" | "allowance" | "approve" | "balanceOf" | "decimals" | "feeRate" | "getAmountOut" | "getEquivalentToken1Estimate" | "getEquivalentToken2Estimate" | "getPoolDetails" | "getSwapToken1Estimate" | "getSwapToken2Estimate" | "name" | "owner" | "provide" | "setFee" | "setPoolTokens" | "swapToken1" | "swapToken2" | "symbol" | "token1" | "token2" | "totalSupply" | "totalToken1" | "totalToken2" | "transfer" | "transferFrom" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "Burn" | "Mint" | "Swap" | "Transfer"): EventFragment;

    encodeFunctionData(functionFragment: 'K', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAmountOut', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEquivalentToken1Estimate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEquivalentToken2Estimate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPoolDetails', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSwapToken1Estimate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSwapToken2Estimate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'provide', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPoolTokens', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'swapToken1', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapToken2', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'token1', values?: undefined): string;
encodeFunctionData(functionFragment: 'token2', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalToken1', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalToken2', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'K', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAmountOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEquivalentToken1Estimate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEquivalentToken2Estimate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPoolDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSwapToken1Estimate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSwapToken2Estimate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'provide', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPoolTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapToken1', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapToken2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token1', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalToken1', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalToken2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BurnEvent {
      export type InputTuple = [sender: AddressLike, amount0: BigNumberish, amount1: BigNumberish, to: AddressLike];
      export type OutputTuple = [sender: string, amount0: bigint, amount1: bigint, to: string];
      export interface OutputObject {sender: string, amount0: bigint, amount1: bigint, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintEvent {
      export type InputTuple = [sender: AddressLike, amount0: BigNumberish, amount1: BigNumberish];
      export type OutputTuple = [sender: string, amount0: bigint, amount1: bigint];
      export interface OutputObject {sender: string, amount0: bigint, amount1: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwapEvent {
      export type InputTuple = [sender: AddressLike, amount0In: BigNumberish, amount1In: BigNumberish, amount0Out: BigNumberish, amount1Out: BigNumberish, to: AddressLike];
      export type OutputTuple = [sender: string, amount0In: bigint, amount1In: bigint, amount0Out: bigint, amount1Out: bigint, to: string];
      export interface OutputObject {sender: string, amount0In: bigint, amount1In: bigint, amount0Out: bigint, amount1Out: bigint, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AMM extends BaseContract {
    
    connect(runner?: ContractRunner | null): AMM;
    waitForDeployment(): Promise<this>;

    interface: AMMInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    K: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAmountOut: TypedContractMethod<
      [amountIn: BigNumberish, reserveIn: BigNumberish, reserveOut: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getEquivalentToken1Estimate: TypedContractMethod<
      [amountToken2: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getEquivalentToken2Estimate: TypedContractMethod<
      [amountToken1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getPoolDetails: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint] & {_totalToken1: bigint, _totalToken2: bigint, _totalShares: bigint, _feeRate: bigint }],
      'view'
    >
    

    
    getSwapToken1Estimate: TypedContractMethod<
      [amountToken1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getSwapToken2Estimate: TypedContractMethod<
      [amountToken2: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    provide: TypedContractMethod<
      [amountToken1: BigNumberish, amountToken2: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    setFee: TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPoolTokens: TypedContractMethod<
      [_token1: AddressLike, _token2: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    swapToken1: TypedContractMethod<
      [amountToken1: BigNumberish, minAmountOut: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    swapToken2: TypedContractMethod<
      [amountToken2: BigNumberish, minAmountOut: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    token1: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    token2: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalToken1: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalToken2: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [share: BigNumberish, minAmount1: BigNumberish, minAmount2: BigNumberish, deadline: BigNumberish, ],
      [[bigint, bigint] & {amountToken1: bigint, amountToken2: bigint }],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'K'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAmountOut'): TypedContractMethod<
      [amountIn: BigNumberish, reserveIn: BigNumberish, reserveOut: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getEquivalentToken1Estimate'): TypedContractMethod<
      [amountToken2: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getEquivalentToken2Estimate'): TypedContractMethod<
      [amountToken1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPoolDetails'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint] & {_totalToken1: bigint, _totalToken2: bigint, _totalShares: bigint, _feeRate: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getSwapToken1Estimate'): TypedContractMethod<
      [amountToken1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSwapToken2Estimate'): TypedContractMethod<
      [amountToken2: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'provide'): TypedContractMethod<
      [amountToken1: BigNumberish, amountToken2: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFee'): TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPoolTokens'): TypedContractMethod<
      [_token1: AddressLike, _token2: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapToken1'): TypedContractMethod<
      [amountToken1: BigNumberish, minAmountOut: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapToken2'): TypedContractMethod<
      [amountToken2: BigNumberish, minAmountOut: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'token1'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'token2'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalToken1'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalToken2'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [share: BigNumberish, minAmount1: BigNumberish, minAmount2: BigNumberish, deadline: BigNumberish, ],
      [[bigint, bigint] & {amountToken1: bigint, amountToken2: bigint }],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'Burn'): TypedContractEvent<BurnEvent.InputTuple, BurnEvent.OutputTuple, BurnEvent.OutputObject>;
getEvent(key: 'Mint'): TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
getEvent(key: 'Swap'): TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'Burn(address,uint256,uint256,address)': TypedContractEvent<BurnEvent.InputTuple, BurnEvent.OutputTuple, BurnEvent.OutputObject>;
      Burn: TypedContractEvent<BurnEvent.InputTuple, BurnEvent.OutputTuple, BurnEvent.OutputObject>;
    

      'Mint(address,uint256,uint256)': TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
      Mint: TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
    

      'Swap(address,uint256,uint256,uint256,uint256,address)': TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
      Swap: TypedContractEvent<SwapEvent.InputTuple, SwapEvent.OutputTuple, SwapEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    
    };
  }